/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;
import Modelo.Clientes;

/**
 *
 * @author 36127512021.2
 */
public class ExibirEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form ExibirEmprestimo
     */
    public ExibirEmprestimo() {
        initComponents();
    }
    public void exportarDados (Clientes model) {
        
        lblnome.setText(model.getNome());
        lblcpf.setText(model.getCpf());
        lblendereco.setText(model.getEndereco());
        lblnomedolivro.setText(model.getNomedolivro());
        lbldataderetirada.setText(model.getDataderetirada());
        lbldatadeentrega.setText(model.getDatadeentrega());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomedolivro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcpf = new javax.swing.JLabel();
        lblendereco = new javax.swing.JLabel();
        lblnomedolivro = new javax.swing.JLabel();
        lbldatadeentrega = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbldataderetirada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("EXIBIÇÃO EMPRESTÍMO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 200, 20);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Data de retirada : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 320, 121, 19);

        nomedolivro.setBackground(new java.awt.Color(0, 0, 0));
        nomedolivro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nomedolivro.setText("Nome  :");
        getContentPane().add(nomedolivro);
        nomedolivro.setBounds(40, 90, 70, 19);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Cpf  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 37, 19);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Endereço :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 80, 19);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Nome do livro :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 270, 110, 19);

        lblnome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblnome);
        lblnome.setBounds(120, 80, 140, 30);

        lblcpf.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblcpf);
        lblcpf.setBounds(130, 150, 180, 20);

        lblendereco.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblendereco);
        lblendereco.setBounds(140, 210, 180, 20);

        lblnomedolivro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblnomedolivro);
        lblnomedolivro.setBounds(150, 260, 150, 30);
        getContentPane().add(lbldatadeentrega);
        lbldatadeentrega.setBounds(170, 360, 160, 30);

        jLabel2.setText("Data de entrega  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 360, 110, 14);
        getContentPane().add(lbldataderetirada);
        lbldataderetirada.setBounds(170, 320, 132, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirEmprestimo().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lbldatadeentrega;
    private javax.swing.JLabel lbldataderetirada;
    private javax.swing.JLabel lblendereco;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblnomedolivro;
    private javax.swing.JLabel nomedolivro;
    // End of variables declaration//GEN-END:variables

}