/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import Modelo.Livros;
/**
 *
 * @author 36127512021.2
 */
public class TelaCadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLivro
     */
    public TelaCadastroLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        numerodeedicao = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tela de cadastro livros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(95, 27, 241, 29);

        jLabel2.setText("Autor :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 80, 34, 14);

        jLabel3.setText("Titulo :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 120, 33, 14);

        jLabel4.setText("Codigo :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 170, 40, 14);

        jLabel5.setText("Preço :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 220, 34, 14);

        jLabel6.setText("Numero de edição :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 257, 93, 14);

        jLabel7.setText("Quantidade :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(62, 296, 63, 14);
        getContentPane().add(autor);
        autor.setBounds(140, 70, 164, 30);
        getContentPane().add(titulo);
        titulo.setBounds(140, 110, 164, 30);
        getContentPane().add(codigo);
        codigo.setBounds(140, 160, 164, 30);
        getContentPane().add(preco);
        preco.setBounds(140, 200, 164, 40);
        getContentPane().add(numerodeedicao);
        numerodeedicao.setBounds(135, 244, 164, 40);
        getContentPane().add(quantidade);
        quantidade.setBounds(135, 293, 164, 30);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(340, 292, 63, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        Livros model = new Livros();
        
        TelaExibirCadastro TEC = new TelaExibirCadastro();
        
        try
	   {
               
             
            String A = autor.getText();
            String T = titulo.getText();
            String C = codigo.getText();
            String P = preco.getText();
            String E = numerodeedicao.getText();
            String Q = quantidade.getText();
            
            
            String url = "jdbc:mysql://localhost/novobdlivros"; 
            String sql = "INSERT INTO novolivros (autor,titulo,codigo,preco,numerodeedicao,quantidade) values ('"+A+"','"+T+"','"+C+"','"+P+"','"+E+"','"+Q+"')";
               
	     Connection conexao = DriverManager.getConnection(url,"root","");

	     PreparedStatement atualizar = conexao.prepareStatement(sql);

	     atualizar.executeUpdate();

	     JOptionPane.showMessageDialog(null,"Atualizado com sucesso!");
    
             
             
           model.setAutor(autor.getText());
           model.setTitulo(titulo.getText());
           model.setCodigo(codigo.getText());
           model.setPreco(preco.getText());
           model.setNumerodeedicao(numerodeedicao.getText());
           model.setQuantidade(quantidade.getText());
           
            TEC.exportarDados(model);
            TEC.setVisible(true);
              
	   }
	  
	   catch(Exception erro) { 
           
              JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           }
        
        
        
    }//GEN-LAST:event_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField numerodeedicao;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quantidade;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
